### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by uvmtbfolmt** [Awoodwhale/GOGOPic#1]
作者可以用Material design ui风格开发吗？

**Comment by Awoodwhale** [comment]
> 作者可以用Material design ui风格开发吗？

作者当时开发的时候都没了解过google的这个规范，也是后来发现有相关组件，现在重构不太可能🤣

**Comment by uvmtbfolmt** [comment]
那Material You可以吗？现在的界面感觉不太好看……

**Comment by Awoodwhale** [comment]
> 那Material You可以吗？现在的界面感觉不太好看……

由于本人学业方面的原因，这个仓库维护的可能性较小了，当初学安卓练手玩玩的，目前的就业方向并非安卓开发。所以若想使用这些UI规范来二次开发我完全支持，直接fork本仓库就行了。
